import { OrderCard } from "../_orders-components/order-card";

export const tabValues = [
  {
    id: 1,
    value: "week",
    label: "Week",
    component: OrderCard,
  },
  {
    id: 2,
    value: "month",
    label: "Month",
  },
  {
    id: 3,
    value: "year",
    label: "Month",
  },
];

export const CustomerOrdersData = [
  {
    id: 1,
    userName: "Liam Johnson",
    email: "liam@example.com",
    type: "Sale",
    status: "Fulfilled",
    date: "2023-06-23",
    amount: "$250.00",
  },
  {
    id: 2,
    userName: "Emma Wilson",
    email: "emma@example.com",
    type: "Return",
    status: "Pending",
    date: "2023-07-01",
    amount: "$150.00",
  },
  {
    id: 3,
    userName: "Oliver Brown",
    email: "oliver@example.com",
    type: "Sale",
    status: "Shipped",
    date: "2023-06-20",
    amount: "$300.00",
  },
  {
    id: 4,
    userName: "Sophia Davis",
    email: "sophia@example.com",
    type: "Sale",
    status: "Cancelled",
    date: "2023-06-18",
    amount: "$100.00",
  },
  {
    id: 5,
    userName: "Noah Smith",
    email: "noah@example.com",
    type: "Exchange",
    status: "Fulfilled",
    date: "2023-06-22",
    amount: "$200.00",
  },
  {
    id: 6,
    userName: "Ava Martinez",
    email: "ava@example.com",
    type: "Sale",
    status: "Fulfilled",
    date: "2023-07-02",
    amount: "$275.00",
  },
  {
    id: 7,
    userName: "James Taylor",
    email: "james@example.com",
    type: "Return",
    status: "Pending",
    date: "2023-07-03",
    amount: "$180.00",
  },
  {
    id: 8,
    userName: "Isabella Garcia",
    email: "isabella@example.com",
    type: "Sale",
    status: "Shipped",
    date: "2023-06-21",
    amount: "$320.00",
  },
  {
    id: 9,
    userName: "William Harris",
    email: "william@example.com",
    type: "Sale",
    status: "Cancelled",
    date: "2023-06-19",
    amount: "$90.00",
  },
  {
    id: 10,
    userName: "Mia Clark",
    email: "mia@example.com",
    type: "Exchange",
    status: "Fulfilled",
    date: "2023-06-24",
    amount: "$210.00",
  },
  {
    id: 11,
    userName: "Elijah Rodriguez",
    email: "elijah@example.com",
    type: "Sale",
    status: "Fulfilled",
    date: "2023-06-25",
    amount: "$260.00",
  },
  {
    id: 12,
    userName: "Charlotte Lee",
    email: "charlotte@example.com",
    type: "Return",
    status: "Pending",
    date: "2023-07-04",
    amount: "$160.00",
  },
  {
    id: 13,
    userName: "Lucas Walker",
    email: "lucas@example.com",
    type: "Sale",
    status: "Shipped",
    date: "2023-06-26",
    amount: "$330.00",
  },
  {
    id: 14,
    userName: "Amelia Young",
    email: "amelia@example.com",
    type: "Sale",
    status: "Cancelled",
    date: "2023-06-27",
    amount: "$95.00",
  },
  {
    id: 15,
    userName: "Ethan Allen",
    email: "ethan@example.com",
    type: "Exchange",
    status: "Fulfilled",
    date: "2023-06-28",
    amount: "$220.00",
  },
];
